### ISSUE TITLE
Hardware Request Card Not Available

### ISSUE THREAD

**Issue by jhauserw3241** [KS-PACT/website#109]
If you request the hardware request card without going through the GUI from the hardware page, it just throws the following error:
Error: Failed to lookup view "hardware_request" in views directory "C:\Users\joyha\Documents\KS-Pact\website\views"
    at EventEmitter.render (C:\Users\joyha\Documents\KS-Pact\website\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\Users\joyha\Documents\KS-Pact\website\node_modules\express\lib\response.js:966:7)
    at db.any.then.data (C:\Users\joyha\Documents\KS-Pact\website\server.js:316:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Instead, it should redirect you to the hardware page.

**Comment by jhauserw3241** [comment]
This error is actually due to the fact that we no longer use the hardware_request page. We replaced it with a modal in a previous commit and forgot to remove the header option for it.
